yolo_model:

  config_file:
    name: yolov3-RobotX_2048.cfg
  weight_file:
    name: yolov3-RobotX_2048_50000.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - greenMarker
      - redMarker
      - whiteMarker
      - miscMarker
      - greenRound
      - orangeRound
      - yellowRound
      - whiteRound
      - blueRound
      - blackRound
      - detectDeliver
      - scanCode
      - dock
      - boat