teleop_twist_joy:
  axis_linear:
    x: 1
    y: 0
  scale_linear:
    x: 0.75
    y: 0.5
  scale_linear_turbo:
    x: 3.0
    y: 1.0
  axis_angular: 2
  scale_angular: -0.5
  scale_angular_turbo: -0.75
  enable_button: 4         # Left shoulder
  enable_turbo_button: 5   # Right shoulder
joy_node:
  deadzone: 0.1
  autorepeat_rate: 20